package com.vitria.oi.monitoring.events;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class MailClient {

	public static void sendMail(String addresses, String project, String state) {
		final String username = "shamis657@gmail.com";
		final String password = "three6two";

		Properties props = new Properties();
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.starttls.enable", "true");
		props.put("mail.smtp.host", "smtp.gmail.com");
		props.put("mail.smtp.port", "587");

		Session session = Session.getInstance(props,
				new javax.mail.Authenticator() {
					protected PasswordAuthentication getPasswordAuthentication() {
						return new PasswordAuthentication(username, password);
					}
				});

		try {
			Message message = new MimeMessage(session);
			message.setFrom(new InternetAddress(username));
			String[] toAddresses = addresses.split("\\|");
			for (String toAddress : toAddresses) {
				message.addRecipient(Message.RecipientType.TO,
						new InternetAddress(toAddress));
			}
			message.setSubject("Project : "+ project +" is in "+ state +" state");
			DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
			Date date = new Date();
			System.out.println(dateFormat.format(date));
			String content = "Project : "
					+ project
					+ " is in "
					+ state
					+ " state. \n\nThis is an autogenerated notification mail.";

			message.setText(content);

			Transport.send(message);
			System.out.println("Mail sent");

		} catch (MessagingException e) {
			e.printStackTrace();
		}
	}
}
